### ISSUE TITLE
Please support subscribeRepos(Streaming)

### ISSUE THREAD

**Issue by lamrongol** [uakihir0/bsky4j#1]
I'm sorry to ask, but could you please enable com.atproto.sync.subscribeRepos, which is like Streaming API for Twitter and Misskey? https://atproto.com/lexicons/com-atproto-sync#comatprotosyncsubscriberepos

http://whenitrains.glitch.me uses this to retrieve all posts for [bsky.social](http://bsky.social/) and the (javascript) source code is below. http://whenitrains.glitch.me/script.mjs
There is also a Python version, but it doesn't seem to actually work: https://acidafghan.glitch.me/script.txt

Edit:
I run http://whenitrains.glitch.me/script.mjs by Deno and send post to my Java program by
Socket.IO and once this is solved.

-----------------------------------------------------------------------------
お願いになってしまい申し訳ないのですが、TwitterやMisskeyのStreaming APIにあたるcom.atproto.sync.subscribeReposを使えるようにしていただけないでしょうか。
https://atproto.com/lexicons/com-atproto-sync#comatprotosyncsubscriberepos

http://whenitrains.glitch.me というサイトではこれを利用して[bsky.social](http://bsky.social/)のすべてのポストを取得しており、(javascriptの)ソースコードは以下です。
http://whenitrains.glitch.me/script.mjs
Python版もありますが実際には動かないようです。
https://acidafghan.glitch.me/script.txt

追記：
http://whenitrains.glitch.me/script.mjs をDenoで動かしSocket.IOでJavaにポストを送ることで一旦解決しました。

**Comment by uakihir0** [comment]
The format of data returned by subscribeRepo is specified such that the entire data is returned in CBOR format with multiple records concatenated, and the record data within the record is returned in CAR format.

The CAR format is quite difficult to handle, especially in Java, and there is currently no library for it. This is very problematic, and because of this problem, this implementation seems to be impossible at present. https://ipld.io/specs/transport/car/ is the CAR specification, but currently only Go and JS have decoding libraries for this.

I think this specification is a bit too radical for the quirks, so I threw a message to the development team. I was wondering if I should make it an issue, but it's just a heads-up before that.

https://staging.bsky.app/profile/uakihir0.com/post/3jtzpl5ufm22s

I've also put up a branch that is being implemented, so I'd appreciate it if you could check it out and hopefully find a way to get it done.

https://github.com/uakihir0/bsky4j/tree/f/add_subscribe_repo

---


subscribeRepo で返ってくるデータの形式について、全体が複数連結された CBOR 形式で返ってきて、その中の record データが CAR 形式で返ってくるような仕様になっています。

CAR 形式は特に Java での扱いにかなりの難があり、ライブラリが現状存在しません。これは非常に問題で、この問題のためにこの実装は現状無理がありそうです。 https://ipld.io/specs/transport/car/ が CAR の仕様なのですが、これは現状 Go と JS しかデコードライブラリが存在しません。

流石にこの仕様はちょっと先鋭的すぎると思うので、開発チームの人にメッセージを投げておきました。 issue にするかちょっと悩んだんですが、その前の頭出しぐらいの意味合いです。

https://staging.bsky.app/profile/uakihir0.com/post/3jtzpl5ufm22s

一応実装中のブランチも上げておいたので、確認して、できれば方法を模索してもらえると嬉しいです。

https://github.com/uakihir0/bsky4j/tree/f/add_subscribe_repo

**Comment by uakihir0** [comment]
とりあえず課題意識を認識してもらった。 (matrix 上での会話の引用)

---

uakihir0
👋 Hi, Bluseky Dev team! 
Regarding the format of data returned by subscribeRepo, could you please consider a common data format, CBOR is still very quirky and CAR seems to be language-bound. It would be great if you could consider this for the sake of the ecosystem.

snarfed
DAG-CBOR and CAR aren't that language bound, there are functional libraries in a number of languages. Go, JavaScript, Python, Rust. 

uakihir0
Thanks for the reply. I am currently trying to write a client library in Java, and while CBOR had a publicly available library, I am having trouble finding a library for CAR. I consider it somewhat uncommon from that point of view.

snarfed
Java, maybe so. you could be the first!
ATProto is pretty deeply bought into the IPLD stack at this point, including DAG-CBOR etc. it seems pretty unlikely that they'd switch to something else anytime soon

uakihir0
Understood, it would be helpful if you could just recognize that there are programming languages that do not handle subscribeRepo well.

snarfed
definitely! acknowedged

**Comment by uakihir0** [comment]
#2 

---

ちょっと通信量が増えるけど、subscribeRepo に対応しました。CAR でエンコードされたデータをデコードするのを諦めて getRecord で再取得するという方法で回避しました。

---

I gave up on decoding CAR-encoded data and used getRecord to retrieve it.

**Comment by lamrongol** [comment]
I am sorry that you have implemented it, but like Misskey4j, EOFException seems to occur frequently and connection is broken. WebSocket itself may be difficult in Java, but I'm just reporting it.
--------------------------------
実装して頂いて申し訳ないのですが、Misskey4jと同じく度々EOFExceptionが発生して通信が途切れるようです。ひょっとしたらJavaでWebSocketを使うこと自体難しいかもしれませんが一応報告まで。

**Comment by uakihir0** [comment]
Since the WebSocket communication environment is a home-grown one, we would like to prepare a library that replaces it with a well-known library. I would like to ask you to check the operation with it.

----

WebSocket の通信周りが自作なものなので、名のしれたライブラリに置換したものを用意したいと思います。ちょっとそれで動作確認お願いしたいです。

**Comment by lamrongol** [comment]
You could use the method used by BigBone (https://github.com/andregasser/bigbone, formerly Mastodon4j). Though the connection sometimes interrupted here too.
-----------------------------------------------------------
BigBone( https://github.com/andregasser/bigbone, 旧Mastodon4j)で使われてる方法を使えばいいかもしれません。こっちもたまに通信が途切れますが。
